"""add department field to users model

Revision ID: 24e82e9079c0
Revises: fb5e60bab94c
Create Date: 2026-03-28 09:44:32.897311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e82e9079c0'
down_revision: Union[str, Sequence[str], None] = 'fb5e60bab94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True, comment="e.g. 'Fraud Investigation', 'Data Science', 'Compliance'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
