"""initial_migration

Revision ID: 50c9e33248b8
Revises: 
Create Date: 2026-03-14 23:57:40.866578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50c9e33248b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Permission code, e.g. 'create_case'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment="'claims' | 'fraud' | 'cases' | 'admin' | 'analytics'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True, comment="Unit of measure: 'per bag', 'per km', 'each', 'per m²', etc."),
    sa.Column('avg_price', sa.Float(), nullable=False, comment='Market average price in KES.'),
    sa.Column('min_price', sa.Float(), nullable=True, comment='Observed minimum price in KES.'),
    sa.Column('max_price', sa.Float(), nullable=True, comment='Observed maximum price in KES.'),
    sa.Column('std_dev', sa.Float(), nullable=True, comment='Standard deviation for z-score anomaly detection.'),
    sa.Column('source', sa.String(length=300), nullable=True, comment="e.g. 'Kenya Treasury Price Schedule 2025', 'PPIP Historical Awards'"),
    sa.Column('county', sa.String(length=100), nullable=True, comment='For region-specific benchmarks; null = national average.'),
    sa.Column('year', sa.Integer(), nullable=True, comment='Reference year for this price data.'),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_benchmarks_category'), 'price_benchmarks', ['category'], unique=False)
    op.create_index('ix_price_benchmarks_item_category', 'price_benchmarks', ['item_name', 'category'], unique=False)
    op.create_index(op.f('ix_price_benchmarks_item_name'), 'price_benchmarks', ['item_name'], unique=False)
    op.create_table('procuring_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='EntityType enum value: ministry / county_government / state_corporation …'),
    sa.Column('county', sa.String(length=100), nullable=True, comment='For county-level entities; null for national ministries.'),
    sa.Column('code', sa.String(length=50), nullable=True, comment="Official PPIP entity code e.g. 'NT', 'NRB-CGV'"),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('corruption_history_score', sa.Float(), nullable=False, comment='Rolling average risk score across all past tenders (0–100).'),
    sa.Column('investigation_count', sa.Integer(), nullable=False, comment='Number of confirmed EACC investigations involving this entity.'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_procuring_entities_county'), 'procuring_entities', ['county'], unique=False)
    op.create_index(op.f('ix_procuring_entities_name'), 'procuring_entities', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Role name, e.g. 'fraud_analyst'"),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='System roles cannot be deleted via the UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True, comment='Companies Registry registration number'),
    sa.Column('kra_pin', sa.String(length=50), nullable=True, comment='Kenya Revenue Authority Personal Identification Number'),
    sa.Column('incorporation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_age_days', sa.Integer(), nullable=True, comment='Computed from incorporation_date; updated on supplier refresh.'),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('tax_filings_count', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('has_physical_address', sa.Boolean(), nullable=True),
    sa.Column('has_online_presence', sa.Boolean(), nullable=True),
    sa.Column('past_contracts_count', sa.Integer(), nullable=False),
    sa.Column('past_contracts_value', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Composite ghost-supplier risk score (0–100); written by risk engine.'),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_county'), 'suppliers', ['county'], unique=False)
    op.create_index(op.f('ix_suppliers_is_blacklisted'), 'suppliers', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_suppliers_kra_pin'), 'suppliers', ['kra_pin'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_registration_number'), 'suppliers', ['registration_number'], unique=True)
    op.create_index(op.f('ix_suppliers_risk_score'), 'suppliers', ['risk_score'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser bypasses all permission checks'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts — lock account after threshold'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this datetime after too many failed logins'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL for system-initiated actions'),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'TOKEN_REFRESHED', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_DEACTIVATED', 'ROLE_ASSIGNED', 'ROLE_REMOVED', 'TENDER_CREATED', 'TENDER_UPDATED', 'TENDER_SCORED', 'SCORE_OVERRIDDEN', 'BID_SUBMITTED', 'BID_UPDATED', 'FEATURES_RECOMPUTED', 'FEATURES_OVERRIDDEN', 'CASE_CREATED', 'CASE_ASSIGNED', 'CASE_STATUS_UPDATED', 'CASE_NOTE_ADDED', 'CASE_CLOSED', 'RULE_CREATED', 'RULE_UPDATED', 'RULE_TOGGLED', 'MODEL_REGISTERED', 'MODEL_DEPLOYED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment="e.g. 'Claim', 'FraudCase', 'User'"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='PK of the affected record'),
    sa.Column('audit_log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary context — diff, old/new values, request IP, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_performed_at', 'audit_logs', ['performed_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('directors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True, comment='Kenya National ID or passport number; used for watchlist matching.'),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role_title', sa.String(length=100), nullable=True, comment="e.g. 'Managing Director', 'Chairperson', 'Secretary'"),
    sa.Column('is_politically_exposed', sa.Boolean(), nullable=False, comment='True if director is a PEP — raises corruption risk score.'),
    sa.Column('pep_details', sa.String(length=500), nullable=True, comment='Free-text description of political exposure if is_politically_exposed=True.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directors_is_politically_exposed'), 'directors', ['is_politically_exposed'], unique=False)
    op.create_index(op.f('ix_directors_national_id'), 'directors', ['national_id'], unique=False)
    op.create_index(op.f('ix_directors_supplier_id'), 'directors', ['supplier_id'], unique=False)
    op.create_index('ix_directors_supplier_national_id', 'directors', ['supplier_id', 'national_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the raw refresh token — never store the raw value'),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='token_type_enum'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE')
    )
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=200), nullable=True, comment="Official PPIP / Gazette reference e.g. 'KEBS/OT/2026/001'"),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment='TenderCategory enum value: works / goods / services / ict …'),
    sa.Column('category_raw', sa.String(length=200), nullable=True, comment='Original scraped category string before normalisation.'),
    sa.Column('estimated_value', sa.Float(), nullable=True, comment='Estimated contract value in KES.'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('procurement_method', sa.String(length=50), nullable=True, comment='ProcurementMethod enum value per PPADA 2015.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True, comment='Date bids are publicly opened.'),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True, comment="Data source identifier: 'ppip' / 'gazette' / 'manual'"),
    sa.Column('is_scraped', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['procuring_entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_category'), 'tenders', ['category'], unique=False)
    op.create_index(op.f('ix_tenders_county'), 'tenders', ['county'], unique=False)
    op.create_index('ix_tenders_county_category', 'tenders', ['county', 'category'], unique=False)
    op.create_index('ix_tenders_county_status', 'tenders', ['county', 'status'], unique=False)
    op.create_index('ix_tenders_created_at', 'tenders', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenders_entity_id'), 'tenders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_tenders_estimated_value'), 'tenders', ['estimated_value'], unique=False)
    op.create_index(op.f('ix_tenders_procurement_method'), 'tenders', ['procurement_method'], unique=False)
    op.create_index(op.f('ix_tenders_reference_number'), 'tenders', ['reference_number'], unique=True)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_title'), 'tenders', ['title'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('PRICE_INFLATION', 'GHOST_SUPPLIER', 'SPECIFICATION_TAILORING', 'CONFLICT_OF_INTEREST', 'CARTEL_ACTIVITY', name='alertflagtype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('under_investigation', sa.Boolean(), nullable=False),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_flag_type'), 'alerts', ['flag_type'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_tender_id'), 'alerts', ['tender_id'], unique=False)
    op.create_index(op.f('ix_alerts_under_investigation'), 'alerts', ['under_investigation'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False, comment='Bid amount in KES.'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_text', sa.Text(), nullable=True, comment='Full proposal text; fed to TF-IDF collusion analysis.'),
    sa.Column('similarity_score', sa.Float(), nullable=True, comment='Max cosine similarity vs all other bids on this tender (0–1). Values above 0.75 indicate potential collusion.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('financial_score', sa.Float(), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'supplier_id', name='uq_bid_tender_supplier')
    )
    op.create_index(op.f('ix_bids_is_winner'), 'bids', ['is_winner'], unique=False)
    op.create_index(op.f('ix_bids_supplier_id'), 'bids', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_bids_tender_id'), 'bids', ['tender_id'], unique=False)
    op.create_index('ix_bids_tender_is_winner', 'bids', ['tender_id', 'is_winner'], unique=False)
    op.create_index('ix_bids_tender_similarity', 'bids', ['tender_id', 'similarity_score'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('contract_value', sa.Float(), nullable=False, comment='Final awarded contract value in KES.'),
    sa.Column('original_tender_value', sa.Float(), nullable=True, comment='Estimated value from the tender at publication time.'),
    sa.Column('value_variation_pct', sa.Float(), nullable=True, comment='((contract_value - original_tender_value) / original_tender_value) × 100. High values indicate post-award price manipulation.'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True, comment='Actual completion date; may differ from end_date.'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('variation_count', sa.Integer(), nullable=False, comment='Number of contract addenda/variations issued post-award.'),
    sa.Column('variation_notes', sa.Text(), nullable=True, comment='Justification notes for contract variations.'),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_supplier_id'), 'contracts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_contracts_tender_id'), 'contracts', ['tender_id'], unique=True)
    op.create_table('red_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=50), nullable=False, comment='FlagType enum value.'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='FlagSeverity enum value.'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description shown in the frontend flag card.'),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured supporting data — schema varies by flag_type (see docstring).'),
    sa.Column('source_model', sa.String(length=100), nullable=True, comment="ML model that generated this flag e.g. 'isolation_forest', 'spacy_ner', 'xgboost'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_flags_flag_type'), 'red_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_red_flags_severity'), 'red_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_red_flags_tender_id'), 'red_flags', ['tender_id'], unique=False)
    op.create_index('ix_red_flags_tender_severity', 'red_flags', ['tender_id', 'severity'], unique=False)
    op.create_index('ix_red_flags_type_severity', 'red_flags', ['flag_type', 'severity'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('price_score', sa.Float(), nullable=False),
    sa.Column('supplier_score', sa.Float(), nullable=False),
    sa.Column('spec_score', sa.Float(), nullable=False),
    sa.Column('contract_value_score', sa.Float(), nullable=False),
    sa.Column('entity_history_score', sa.Float(), nullable=False),
    sa.Column('collusion_score', sa.Float(), nullable=False),
    sa.Column('xgb_score', sa.Float(), nullable=True, comment='XGBoost classifier output (0–100). Null until POST /api/ml/train/xgboost-synthetic.'),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of human-readable flag strings e.g. ["Price 340% above benchmark"]'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='Claude claude-opus-4-6 narrative risk analysis in Markdown.'),
    sa.Column('recommended_action', sa.Text(), nullable=True, comment='Claude-generated recommended next step for investigators.'),
    sa.Column('models_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Which ML models ran e.g. {"price_anomaly": true, "xgboost": false}'),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_risk_level'), 'risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_scores_tender_id'), 'risk_scores', ['tender_id'], unique=True)
    op.create_index(op.f('ix_risk_scores_total_score'), 'risk_scores', ['total_score'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True, comment='Relative path in the file storage volume.'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment="e.g. 'application/pdf', 'application/vnd.openxmlformats-officedocument'"),
    sa.Column('doc_type', sa.String(length=50), nullable=True, comment='DocumentType enum value.'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='OCR / pdfplumber output; fed to spec analysis and collusion detection.'),
    sa.Column('extraction_status', sa.String(length=20), nullable=False, comment='pending / done / failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_table('whistleblower_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('tender_reference', sa.String(length=200), nullable=True, comment='Free-text tender reference entered by reporter; may not match a real tender.'),
    sa.Column('report_text', sa.Text(), nullable=False, comment='Primary allegation description. Minimum 50 characters enforced in schema.'),
    sa.Column('allegation_type', sa.String(length=50), nullable=True, comment='AllegationType enum value — set by reporter or corrected by AI triage.'),
    sa.Column('entity_name', sa.String(length=500), nullable=True, comment='Name of the procuring entity as entered by reporter.'),
    sa.Column('evidence_description', sa.Text(), nullable=True, comment="Reporter's description of supporting evidence they hold."),
    sa.Column('ai_triage_summary', sa.Text(), nullable=True, comment="Claude's narrative summary of the allegation and its credibility."),
    sa.Column('credibility_score', sa.Float(), nullable=True, comment='AI-assessed credibility 0–100. Reports >= 60 surface to investigators.'),
    sa.Column('urgency', sa.String(length=20), nullable=True, comment='WhistleblowerUrgency enum value set by AI triage.'),
    sa.Column('is_credible', sa.Boolean(), nullable=True, comment="Investigator's final credibility judgement (may differ from AI score)."),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True, comment='Investigator who reviewed this report.'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wb_reports_credibility_reviewed', 'whistleblower_reports', ['credibility_score', 'is_reviewed'], unique=False)
    op.create_index('ix_wb_reports_urgency_reviewed', 'whistleblower_reports', ['urgency', 'is_reviewed'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_allegation_type'), 'whistleblower_reports', ['allegation_type'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_credibility_score'), 'whistleblower_reports', ['credibility_score'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_is_reviewed'), 'whistleblower_reports', ['is_reviewed'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_tender_id'), 'whistleblower_reports', ['tender_id'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_urgency'), 'whistleblower_reports', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whistleblower_reports_urgency'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_tender_id'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_is_reviewed'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_credibility_score'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_allegation_type'), table_name='whistleblower_reports')
    op.drop_index('ix_wb_reports_urgency_reviewed', table_name='whistleblower_reports')
    op.drop_index('ix_wb_reports_credibility_reviewed', table_name='whistleblower_reports')
    op.drop_table('whistleblower_reports')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_risk_scores_total_score'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_tender_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_risk_level'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_red_flags_type_severity', table_name='red_flags')
    op.drop_index('ix_red_flags_tender_severity', table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_tender_id'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_severity'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_flag_type'), table_name='red_flags')
    op.drop_table('red_flags')
    op.drop_index(op.f('ix_contracts_tender_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_supplier_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_bids_tender_similarity', table_name='bids')
    op.drop_index('ix_bids_tender_is_winner', table_name='bids')
    op.drop_index(op.f('ix_bids_tender_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_supplier_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_is_winner'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_alerts_under_investigation'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tender_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_flag_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenders_title'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_reference_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_procurement_method'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_estimated_value'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_entity_id'), table_name='tenders')
    op.drop_index('ix_tenders_created_at', table_name='tenders')
    op.drop_index('ix_tenders_county_status', table_name='tenders')
    op.drop_index('ix_tenders_county_category', table_name='tenders')
    op.drop_index(op.f('ix_tenders_county'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_category'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_directors_supplier_national_id', table_name='directors')
    op.drop_index(op.f('ix_directors_supplier_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_national_id'), table_name='directors')
    op.drop_index(op.f('ix_directors_is_politically_exposed'), table_name='directors')
    op.drop_table('directors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_performed_at', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_risk_score'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_registration_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_kra_pin'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_blacklisted'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_county'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_index(op.f('ix_procuring_entities_name'), table_name='procuring_entities')
    op.drop_index(op.f('ix_procuring_entities_county'), table_name='procuring_entities')
    op.drop_table('procuring_entities')
    op.drop_index(op.f('ix_price_benchmarks_item_name'), table_name='price_benchmarks')
    op.drop_index('ix_price_benchmarks_item_category', table_name='price_benchmarks')
    op.drop_index(op.f('ix_price_benchmarks_category'), table_name='price_benchmarks')
    op.drop_table('price_benchmarks')
    op.drop_table('permissions')
    # ### end Alembic commands ###
