"""add procurement entity & bids models

Revision ID: 7a8a8963f1b9
Revises: d21bbbc6b324
Create Date: 2026-03-09 14:33:03.225843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a8a8963f1b9'
down_revision: Union[str, Sequence[str], None] = 'd21bbbc6b324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procuring_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('total_tenders', sa.Integer(), nullable=False),
    sa.Column('total_expenditure', sa.Float(), nullable=False),
    sa.Column('flagged_tenders', sa.Integer(), nullable=False),
    sa.Column('average_corruption_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_procuring_entities_entity_code'), 'procuring_entities', ['entity_code'], unique=True)
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('quote_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('delivery_timeline', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=False),
    sa.Column('warranty', sa.String(length=200), nullable=True),
    sa.Column('technical_proposal', sa.Text(), nullable=True),
    sa.Column('risk_mitigation', sa.Text(), nullable=True),
    sa.Column('quality_approach', sa.Text(), nullable=True),
    sa.Column('technical_documents', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_documents', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_documents', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('bid_reference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_bids_bid_reference'), 'bids', ['bid_reference'], unique=True)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_index(op.f('ix_bids_supplier_id'), 'bids', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_bids_tender_id'), 'bids', ['tender_id'], unique=False)
    op.add_column('tenders', sa.Column('procuring_entity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tenders_procuring_entity_id'), 'tenders', ['procuring_entity_id'], unique=False)
    op.create_foreign_key(None, 'tenders', 'procuring_entities', ['procuring_entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenders', type_='foreignkey')
    op.drop_index(op.f('ix_tenders_procuring_entity_id'), table_name='tenders')
    op.drop_column('tenders', 'procuring_entity_id')
    op.drop_index(op.f('ix_bids_tender_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_supplier_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index(op.f('ix_bids_bid_reference'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_procuring_entities_entity_code'), table_name='procuring_entities')
    op.drop_table('procuring_entities')
    # ### end Alembic commands ###
