"""increase entity_code and entity_type column sizes

Revision ID: 95a3326e1bae
Revises: 7a8a8963f1b9
Create Date: 2026-03-09 15:09:36.130973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a3326e1bae'
down_revision: Union[str, Sequence[str], None] = '7a8a8963f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bids', ['id'])
    op.alter_column('procuring_entities', 'entity_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('procuring_entities', 'entity_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'procuring_entities', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procuring_entities', type_='unique')
    op.alter_column('procuring_entities', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('procuring_entities', 'entity_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'bids', type_='unique')
    # ### end Alembic commands ###
