"""add user roles & permissions models

Revision ID: ca90744e1234
Revises: f8e6bea07921
Create Date: 2026-03-03 11:38:13.988720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca90744e1234'
down_revision: Union[str, Sequence[str], None] = 'f8e6bea07921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_market_prices_category'), 'market_prices', ['category'], unique=False)
    op.create_index(op.f('ix_market_prices_effective_date'), 'market_prices', ['effective_date'], unique=False)
    op.create_index(op.f('ix_market_prices_is_active'), 'market_prices', ['is_active'], unique=False)
    op.create_index(op.f('ix_market_prices_item_name'), 'market_prices', ['item_name'], unique=False)
    op.create_index(op.f('ix_market_prices_location'), 'market_prices', ['location'], unique=False)
    op.create_table(
        "network_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "node_type",
            sa.Enum(
                "SUPPLIER",
                "DIRECTOR",
                "OFFICIAL",
                "COMPANY",
                name="networknodetype",
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("node_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "node_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f('ix_network_nodes_node_id'), 'network_nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_network_nodes_node_type'), 'network_nodes', ['node_type'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Permission code, e.g. 'create_case'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True, comment="'claims' | 'fraud' | 'cases' | 'admin' | 'analytics'"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Role name, e.g. 'fraud_analyst'"),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='System roles cannot be deleted via the UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('year_registered', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('tax_pin', sa.String(length=50), nullable=True),
    sa.Column('tax_compliant', sa.Boolean(), nullable=False),
    sa.Column('tax_compliance_date', sa.Date(), nullable=True),
    sa.Column('nca_registration_number', sa.String(length=100), nullable=True),
    sa.Column('nca_category', sa.String(length=50), nullable=True),
    sa.Column('supply_category', sa.String(length=100), nullable=True),
    sa.Column('agpo_group', sa.String(length=100), nullable=True),
    sa.Column('agpo_cert_number', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('postal_address', sa.String(length=200), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_person_name', sa.String(length=200), nullable=True),
    sa.Column('contact_person_title', sa.String(length=100), nullable=True),
    sa.Column('directors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('beneficial_owners', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True),
    sa.Column('is_ghost_likely', sa.Boolean(), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('total_contracts_won', sa.Integer(), nullable=False),
    sa.Column('total_contract_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('performance_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_county'), 'suppliers', ['county'], unique=False)
    op.create_index(op.f('ix_suppliers_is_blacklisted'), 'suppliers', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_suppliers_is_ghost_likely'), 'suppliers', ['is_ghost_likely'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_registration_number'), 'suppliers', ['registration_number'], unique=True)
    op.create_index(op.f('ix_suppliers_risk_score'), 'suppliers', ['risk_score'], unique=False)
    op.create_index(op.f('ix_suppliers_tax_pin'), 'suppliers', ['tax_pin'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Superuser bypasses all permission checks'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='Consecutive failed login attempts — lock account after threshold'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this datetime after too many failed logins'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='NULL for system-initiated actions'),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'TOKEN_REFRESHED', 'PASSWORD_CHANGED', 'USER_CREATED', 'USER_UPDATED', 'USER_DEACTIVATED', 'ROLE_ASSIGNED', 'ROLE_REMOVED', 'CLAIM_SCORED', 'SCORE_OVERRIDDEN', 'CASE_CREATED', 'CASE_ASSIGNED', 'CASE_STATUS_UPDATED', 'CASE_NOTE_ADDED', 'CASE_CLOSED', 'RULE_CREATED', 'RULE_UPDATED', 'RULE_TOGGLED', 'MODEL_REGISTERED', 'MODEL_DEPLOYED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment="e.g. 'Claim', 'FraudCase', 'User'"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='PK of the affected record'),
    sa.Column('audit_log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary context — diff, old/new values, request IP, etc.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_performed_at', 'audit_logs', ['performed_at'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('network_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('DIRECTOR', 'SHAREHOLDER', 'EMPLOYEE', 'FAMILY_MEMBER', name='networkrelationshiptype'), nullable=False),
    sa.Column('edge_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['network_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['network_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_network_edges_is_active'), 'network_edges', ['is_active'], unique=False)
    op.create_index(op.f('ix_network_edges_relationship_type'), 'network_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_network_edges_source_node_id'), 'network_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_network_edges_target_node_id'), 'network_edges', ['target_node_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the raw refresh token — never store the raw value'),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='token_type_enum'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE')
    )
    op.create_table('supplier_verification_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.Enum('REGISTRATION_AGE', 'PHYSICAL_ADDRESS', 'TAX_COMPLIANCE', 'NCA_REGISTRATION', 'DIRECTOR_VERIFICATION', 'BLACKLIST_CHECK', name='verificationchecktype'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_supplier_verification_checks_check_type'), 'supplier_verification_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_supplier_verification_checks_supplier_id'), 'supplier_verification_checks', ['supplier_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_requirements', sa.Text(), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('procurement_method', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_of_funds', sa.String(length=100), nullable=True),
    sa.Column('tender_security_form', sa.String(length=100), nullable=True),
    sa.Column('tender_security_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('awarded_supplier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'AWARDED', 'CANCELLED', name='tenderstatus'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('source_document_path', sa.String(length=500), nullable=True),
    sa.Column('source_document_type', sa.String(length=20), nullable=True),
    sa.Column('items', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('specifications', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bidders', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tenders_category'), 'tenders', ['category'], unique=False)
    op.create_index(op.f('ix_tenders_county'), 'tenders', ['county'], unique=False)
    op.create_index(op.f('ix_tenders_entity_name'), 'tenders', ['entity_name'], unique=False)
    op.create_index(op.f('ix_tenders_is_flagged'), 'tenders', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_tenders_risk_score'), 'tenders', ['risk_score'], unique=False)
    op.create_index(op.f('ix_tenders_status'), 'tenders', ['status'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('whistleblower_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anonymous_id', sa.String(length=100), nullable=False),
    sa.Column('tracking_id', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('PRICE_INFLATION', 'GHOST_SUPPLIER', 'CONFLICT_OF_INTEREST', 'BRIBERY', name='reportcategory'), nullable=False),
    sa.Column('tender_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_files', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='reportstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='reportpriority'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_whistleblower_reports_anonymous_id'), 'whistleblower_reports', ['anonymous_id'], unique=True)
    op.create_index(op.f('ix_whistleblower_reports_category'), 'whistleblower_reports', ['category'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_status'), 'whistleblower_reports', ['status'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_submitted_at'), 'whistleblower_reports', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_tender_number'), 'whistleblower_reports', ['tender_number'], unique=False)
    op.create_index(op.f('ix_whistleblower_reports_tracking_id'), 'whistleblower_reports', ['tracking_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('PRICE_INFLATION', 'GHOST_SUPPLIER', 'SPECIFICATION_TAILORING', 'CONFLICT_OF_INTEREST', 'CARTEL_ACTIVITY', name='alertflagtype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('under_investigation', sa.Boolean(), nullable=False),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_flag_type'), 'alerts', ['flag_type'], unique=False)
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_tender_id'), 'alerts', ['tender_id'], unique=False)
    op.create_index(op.f('ix_alerts_under_investigation'), 'alerts', ['under_investigation'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('PRICE_INFLATION', 'SUPPLIER_VERIFICATION', 'SPECIFICATION_ANALYSIS', 'NETWORK_ANALYSIS', 'ML_RISK_SCORING', name='analysistype'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='risklevel'), nullable=True),
    sa.Column('findings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_version', sa.String(length=20), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_type'), 'analysis_results', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_results_analyzed_at'), 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_tender_id'), 'analysis_results', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_tender_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analyzed_at'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analysis_type'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_alerts_under_investigation'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tender_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_flag_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_whistleblower_reports_tracking_id'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_tender_number'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_submitted_at'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_status'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_category'), table_name='whistleblower_reports')
    op.drop_index(op.f('ix_whistleblower_reports_anonymous_id'), table_name='whistleblower_reports')
    op.drop_table('whistleblower_reports')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_risk_score'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_flagged'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_entity_name'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_county'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_category'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_supplier_verification_checks_supplier_id'), table_name='supplier_verification_checks')
    op.drop_index(op.f('ix_supplier_verification_checks_check_type'), table_name='supplier_verification_checks')
    op.drop_table('supplier_verification_checks')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_network_edges_target_node_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_source_node_id'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_relationship_type'), table_name='network_edges')
    op.drop_index(op.f('ix_network_edges_is_active'), table_name='network_edges')
    op.drop_table('network_edges')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_performed_at', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_tax_pin'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_risk_score'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_registration_number'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_ghost_likely'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_blacklisted'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_county'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_network_nodes_node_type'), table_name='network_nodes')
    op.drop_index(op.f('ix_network_nodes_node_id'), table_name='network_nodes')
    op.drop_table('network_nodes')
    op.drop_index(op.f('ix_market_prices_location'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_item_name'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_is_active'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_effective_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_category'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
