"""add attachements field to tenders

Revision ID: d21bbbc6b324
Revises: ca90744e1234
Create Date: 2026-03-03 15:20:01.022334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd21bbbc6b324'
down_revision: Union[str, Sequence[str], None] = 'ca90744e1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alerts', ['id'])
    op.create_unique_constraint(None, 'analysis_results', ['id'])
    op.create_unique_constraint(None, 'market_prices', ['id'])
    op.create_unique_constraint(None, 'network_edges', ['id'])
    op.create_unique_constraint(None, 'network_nodes', ['id'])
    op.create_unique_constraint(None, 'supplier_verification_checks', ['id'])
    op.create_unique_constraint(None, 'suppliers', ['id'])
    op.add_column('tenders', sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'tenders', ['id'])
    op.create_unique_constraint(None, 'whistleblower_reports', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whistleblower_reports', type_='unique')
    op.drop_constraint(None, 'tenders', type_='unique')
    op.drop_column('tenders', 'attachments')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'supplier_verification_checks', type_='unique')
    op.drop_constraint(None, 'network_nodes', type_='unique')
    op.drop_constraint(None, 'network_edges', type_='unique')
    op.drop_constraint(None, 'market_prices', type_='unique')
    op.drop_constraint(None, 'analysis_results', type_='unique')
    op.drop_constraint(None, 'alerts', type_='unique')
    # ### end Alembic commands ###
