"""rename procuring_entity to entity_name, submission_deadline to deadline

Revision ID: f8e6bea07921
Revises: 738357f34994
Create Date: 2026-03-01 23:44:27.467760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e6bea07921'
down_revision: Union[str, Sequence[str], None] = '738357f34994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'alerts', ['id'])
    op.create_unique_constraint(None, 'analysis_results', ['id'])
    op.create_unique_constraint(None, 'market_prices', ['id'])
    op.create_unique_constraint(None, 'network_edges', ['id'])
    op.create_unique_constraint(None, 'network_nodes', ['id'])
    op.create_unique_constraint(None, 'supplier_verification_checks', ['id'])
    op.add_column('suppliers', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('year_registered', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('supply_category', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('agpo_group', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('agpo_cert_number', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('county', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('contact_person_name', sa.String(length=200), nullable=True))
    op.add_column('suppliers', sa.Column('contact_person_title', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_suppliers_county'), 'suppliers', ['county'], unique=False)
    op.create_unique_constraint(None, 'suppliers', ['id'])
    op.add_column('tenders', sa.Column('entity_name', sa.String(length=200), nullable=False))
    op.add_column('tenders', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('tenders', sa.Column('procurement_method', sa.String(length=100), nullable=True))
    op.add_column('tenders', sa.Column('source_of_funds', sa.String(length=100), nullable=True))
    op.add_column('tenders', sa.Column('tender_security_form', sa.String(length=100), nullable=True))
    op.add_column('tenders', sa.Column('tender_security_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('tenders', sa.Column('contact_email', sa.String(length=100), nullable=True))
    op.add_column('tenders', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('tenders', sa.Column('opening_date', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_tenders_procuring_entity'), table_name='tenders')
    op.create_index(op.f('ix_tenders_entity_name'), 'tenders', ['entity_name'], unique=False)
    op.create_unique_constraint(None, 'tenders', ['id'])
    op.drop_column('tenders', 'submission_deadline')
    op.drop_column('tenders', 'procuring_entity')
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'whistleblower_reports', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whistleblower_reports', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('tenders', sa.Column('procuring_entity', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('tenders', sa.Column('submission_deadline', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenders', type_='unique')
    op.drop_index(op.f('ix_tenders_entity_name'), table_name='tenders')
    op.create_index(op.f('ix_tenders_procuring_entity'), 'tenders', ['procuring_entity'], unique=False)
    op.drop_column('tenders', 'opening_date')
    op.drop_column('tenders', 'deadline')
    op.drop_column('tenders', 'contact_email')
    op.drop_column('tenders', 'tender_security_amount')
    op.drop_column('tenders', 'tender_security_form')
    op.drop_column('tenders', 'source_of_funds')
    op.drop_column('tenders', 'procurement_method')
    op.drop_column('tenders', 'entity_type')
    op.drop_column('tenders', 'entity_name')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_index(op.f('ix_suppliers_county'), table_name='suppliers')
    op.drop_column('suppliers', 'contact_person_title')
    op.drop_column('suppliers', 'contact_person_name')
    op.drop_column('suppliers', 'county')
    op.drop_column('suppliers', 'agpo_cert_number')
    op.drop_column('suppliers', 'agpo_group')
    op.drop_column('suppliers', 'supply_category')
    op.drop_column('suppliers', 'year_registered')
    op.drop_column('suppliers', 'business_type')
    op.drop_constraint(None, 'supplier_verification_checks', type_='unique')
    op.drop_constraint(None, 'network_nodes', type_='unique')
    op.drop_constraint(None, 'network_edges', type_='unique')
    op.drop_constraint(None, 'market_prices', type_='unique')
    op.drop_constraint(None, 'analysis_results', type_='unique')
    op.drop_constraint(None, 'alerts', type_='unique')
    # ### end Alembic commands ###
