"""add whistleblower model

Revision ID: fb5e60bab94c
Revises: 50c9e33248b8
Create Date: 2026-03-19 10:14:25.210893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5e60bab94c'
down_revision: Union[str, Sequence[str], None] = '50c9e33248b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('tender_ref', sa.String(length=200), nullable=True, comment='Denormalised tender reference for fast display.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open | in_review | escalated | closed'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='critical | high | medium | low — copied from RiskScore at open time.'),
    sa.Column('findings', sa.Text(), nullable=True, comment="Investigator's running notes and key findings."),
    sa.Column('investigator_id', sa.UUID(), nullable=True),
    sa.Column('investigator_name', sa.String(length=255), nullable=True, comment='Denormalised for display without joining users table.'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_investigator_id'), 'investigations', ['investigator_id'], unique=False)
    op.create_index('ix_investigations_opened_at', 'investigations', ['opened_at'], unique=False)
    op.create_index(op.f('ix_investigations_risk_level'), 'investigations', ['risk_level'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index('ix_investigations_status_risk', 'investigations', ['status', 'risk_level'], unique=False)
    op.create_index(op.f('ix_investigations_tender_id'), 'investigations', ['tender_id'], unique=False)
    op.create_unique_constraint(None, 'alerts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='unique')
    op.drop_index(op.f('ix_investigations_tender_id'), table_name='investigations')
    op.drop_index('ix_investigations_status_risk', table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_risk_level'), table_name='investigations')
    op.drop_index('ix_investigations_opened_at', table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigator_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
